language: python
python:
  - "3.8.6"
env:
  - DJANGO=3.1.4 DB=postgresql
install:
  - pip install -r places_remember/requirements.txt
  - pip install coveralls
script:
  - coverage run places_remember/manage.py test
after_success:
  - coveralls
