# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Django application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.10
    - name: psycopg2 prerequisites
      run: sudo apt-get install python-dev libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r places_remember/requirements.txt
    - name: Run migrations
      env:
        SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
      run: python places_remember/manage.py migrate
    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
        ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      run: python places_remember/manage.py test
